version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_demo-zulin
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=demo-zulin
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Aa11223344
      - MYSQL_ADDRESS=10.37.105.91
networks:
  default:
    driver: bridge
